kind: Kustomization
namespace: crd-op-writer
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: mysql-pass
  literals:
  - password=Muzo8080
resources:
  - mysql-deployment.yaml
