apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crd-op-writers.demo.com
  namespace: crd-op-writer
spec:
  group: demo.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["table", "name", "age", "country"]
              properties:
                table:
                  type: string
                name:
                  type: string
                age:
                  type: integer
                country:
                  type: string
  scope: Namespaced
  names:
    plural: crd-op-writers
    singular: crd-op-writer
    kind: CrdOpWriter
    shortNames:
    - cow


    